http.clients:
  todo-client:
    url: https://jsonplaceholder.typicode.com/todos
  user-client:
    url: https://asdasdasd.free.beeceptor.com/users
    headers:
      header1: value1
    cookies:
      cookie1: value1
    filters:
      - filterFunction
